account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("", views.AccountView, name="account"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
]

core/urls.py
from django.urls import path
from core import views, transfer, transaction , payment_request, credit_card

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    
    # Money Transfers
    path("search-account/", transfer.search_users_by_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.amount_transfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/", transfer.amount_transfer_process, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),

    # Transactions
    path("transactions/", transaction.transaction_list, name="transactions"),
    path("transaction-detail/<transaction_id>", transaction.transaction_detail, name="transaction-detail"),
    
    # Paymennt Requests
    path("request-search-users/", payment_request.search_users_request, name="request-search-users"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-process/<account_number>/", payment_request.amount_request_process, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("amount-request-dispatch/<account_number>/<transaction_id>/", payment_request.amount_request_dispatch, name="amount-request-dispatch"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.amount_request_completed, name="amount-request-completed"),
    
    # Payment Request Settlement 
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),

    # Delete Payment Request 
    path("cancel-payment-request/<transaction_id>/", payment_request.cancel_payment_request, name="cancel-payment-request"),

    # Card Details
    path("card/<card_id>/", credit_card.card_detail, name="card-details"),
    path("fund-card/<card_id>/", credit_card.fund_card, name="fund-card"),  
    path("withdraw-from-card/<card_id>/", credit_card.withdraw_from_card, name="withdraw-from-card"),      
    path("remove-card/<card_id>/", credit_card.remove_card, name="remove-card"),    
]

kcoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("user_auths.urls")),
    path("account/", include("account.urls")),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auths/urls.py
from django.urls import path
from user_auths import views

app_name = "user_auths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.LoginView, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>KCoin - Money Transfer and Online Payments</title>
    <link
      rel="shortcut icon"
      href="{% static 'assets/images/fav.png' %}"
      type="image/x-icon"
    /> 
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> {% endcomment %}

    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}" />
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" referrerpolicy="no-referrer" /> {% endcomment %}

    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" />
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/themes/base/jquery-ui.min.css" integrity="sha512-8PjjnSP8Bw/WNPxF6wkklW6qlQJdWJc/3w/ZQPvZ/1bjVDkrrSqLe9mfPYrMxtnzsXFPc434+u4FHLnLjXTSsg==" crossorigin="anonymous" referrerpolicy="no-referrer" /> {% endcomment %}

    <link rel="stylesheet" href="{% static 'assets/css/plugin/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugin/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugin/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/arafat-font.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugin/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  </head>

  <body>
    <!-- start preloader -->
    {% comment %} <div class="preloader" id="preloader"></div> {% endcomment %}
    <!-- end preloader -->

    <!-- Scroll To Top Start-->
    <a href="javascript:void(0)" class="scrollToTop"
      ><i class="fas fa-angle-double-up"></i
    ></a>
    <!-- Scroll To Top End -->

    <!-- header-section start -->
    <header class="header-section">
      <div class="overlay">
        <div class="container">
          <div class="row d-flex header-area">
            <nav class="navbar navbar-expand-lg navbar-light">
              <a class="navbar-brand" href="/">
                <img
                  src="{% static 'assets/images/logo.png' %}"
                  class="logo"
                  alt="logo"
                />
              </a>
              <button
                class="navbar-toggler collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar-content"
              >
                <i class="fas fa-bars"></i>
              </button>
              <div
                class="collapse navbar-collapse justify-content-end"
                id="navbar-content"
              >
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                  <li class="nav-item dropdown main-navbar">
                    <a
                      class="nav-link dropdown-toggle"
                      href="javascript:void(0)"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      >Personal</a
                    >
                    <ul class="dropdown-menu main-menu shadow">
                      <li>
                        <a class="nav-link" href="security.html">Security</a>
                      </li>
                      <li><a class="nav-link" href="fees.html">Fees</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown main-navbar">
                    <a
                      class="nav-link dropdown-toggle"
                      href="javascript:void(0)"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      >Business</a
                    >
                    <ul class="dropdown-menu main-menu shadow">
                      <li>
                        <a class="nav-link" href="payments-01.html"
                          >Business Payments</a
                        >
                      </li>
                      <li>
                        <a class="nav-link" href="business-account.html"
                          >Business Account</a
                        >
                      </li>
                      <li>
                        <a class="nav-link" href="corporate-card.html"
                          >Corporate Card</a
                        >
                      </li>
                      <li>
                        <a class="nav-link" href="invoice-management.html"
                          >Invoice</a
                        >
                      </li>
                      <li>
                        <a class="nav-link" href="rewards.html">Rewards</a>
                      </li>
                      <li><a class="nav-link" href="fees.html">Fees</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown main-navbar">
                    <a
                      class="nav-link dropdown-toggle"
                      href="javascript:void(0)"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      >Company</a
                    >
                    <ul class="dropdown-menu main-menu shadow">
                      <li>
                        <a class="nav-link" href="about-us.html">About Us</a>
                      </li>
                      <li><a class="nav-link" href="career.html">Career</a></li>
                      <li>
                        <a class="nav-link" href="career-details.html"
                          >Career Details</a
                        >
                      </li>
                      <li class="dropend sub-navbar">
                        <a
                          href="javascript:void(0)"
                          class="dropdown-item dropdown-toggle"
                          data-bs-toggle="dropdown"
                          data-bs-auto-close="outside"
                          >Blog</a
                        >
                        <ul class="dropdown-menu sub-menu shadow">
                          <li><a class="nav-link" href="blog.html">Blog</a></li>
                          <li>
                            <a class="nav-link" href="blog-details.html"
                              >Blog Details</a
                            >
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown main-navbar">
                    <a
                      class="nav-link dropdown-toggle"
                      href="javascript:void(0)"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      >Help</a
                    >
                    <ul class="dropdown-menu main-menu shadow">
                      <li>
                        <a class="nav-link" href="help-center.html"
                          >Help Center</a
                        >
                      </li>
                      <li>
                        <a class="nav-link" href="help-center-category.html"
                          >Help Category</a
                        >
                      </li>
                    </ul>
                  </li>
                </ul>
                <div class="right-area header-action d-flex align-items-center max-un">
                  {% comment %} {% if request.user.is_authenticated %}
                    <a href="/admin" class="cmdn-btn"> <small>Admin</small></a>
                    <a href="{% url "user_auths:sign-out" %}" class="login cmn-btn">Sign out</a>
                  {% else %}
                    <a href="{% url "user_auths:sign-in" %}" class="login">Login</a>
                    <a href="{% url "user_auths:sign-up" %}" class="cmn-btn"
                      >Sign Up 
                      &nbsp;
                      <i class="fas fa-caret-right"></i>
                    </a>
                  {% endif %} {% endcomment %}
                  {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                      |&nbsp; <a href="/admin" class="cmdn-btn"> <small><b>Admin</b></small></a> &nbsp;|&nbsp;
                    {% endif %}
                    <a href="{% url "account:dashboard" %}" class="cmdn-btn"> Dashboard</a>
                    <a href="{% url "user_auths:sign-out" %}" class="login cmn-btn">Sign out</a>
                  {% else %}
                    <a href="{% url "user_auths:sign-in" %}" class="login">Login</a>
                    <a href="{% url "user_auths:sign-up" %}" class="cmn-btn">Sign Up &nbsp; <i class="fas fa-caret-right"></i></a>
                  {% endif %}
                </div>
              </div>
            </nav>
          </div>
          {% comment %} Alert Start {% endcomment %}
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
              <strong>{{message}}</strong> 
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div> 
            {% endfor %}
          {% endif %}
          {% comment %} Alert End {% endcomment %}
        </div>
      </div>
    </header>
    <!-- header-section end -->

    {% block content %}{% endblock content %}

    <!--==================================================================-->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> {% endcomment %}

    <script src="{% static 'assets/js/fontawesome.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js" integrity="sha512-UwcC/iaz5ziHX7V6LjSKaXgCuRRqbTp1QHpbOJ4l1nw2/boCfZ2KlFIqBUA/uRVF0onbREnY9do8rM/uT/ilqw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}
    
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}

    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/jquery-ui.min.js" integrity="sha512-Ww1y9OuQ2kehgVWSD/3nhgfrb424O3802QYP/A5gPXoM4+rRjiKrjHdGxQKrMGQykmsJ/86oGdHszfcVgUr4hA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}

    <script src="{% static 'assets/js/plugin/waypoint.min.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/noframework.waypoints.min.js" integrity="sha512-fHXRw0CXruAoINU11+hgqYvY/PcsOWzmj0QmcSOtjlJcqITbPyypc8cYpidjPurWpCnlB8VKfRwx6PIpASCUkQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>     {% endcomment %}

    <script src="{% static 'assets/js/plugin/counter.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.js" integrity="sha512-+/4Q+xH9jXbMNJzNt2eMrYv/Zs2rzr4Bu2thfvzlshZBvH1g+VGP55W8b6xfku0c0KknE7qlbBPhDPrHFbgK4g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}

    <script src="{% static 'assets/js/plugin/jquery.magnific-popup.min.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js" integrity="sha512-IsNh5E3eYy3tr/JiX2Yx4vsCujtkhwl7SLqgnwLNgf04Hrt9BT9SXlLlZlWx+OK4ndzAoALhsMNcCmkggjZB1w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}
  
    <script src="{% static 'assets/js/plugin/slick.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.0/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}
    
    <script src="{% static 'assets/js/plugin/wow.min.js' %}"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}

    <script src="{% static 'assets/js/plugin/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/plugin.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>