account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [
    path("", views.AccountView, name="account"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("kyc-reg/", views.kyc_registration, name="kyc-reg"),
]

core/urls.py
from django.urls import path
from core import views, transfer, transaction , payment_request, credit_card

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    
    # Money Transfers
    path("search-account/", transfer.search_users_by_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.amount_transfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/", transfer.amount_transfer_process, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),

    # Transactions
    path("transactions/", transaction.transaction_list, name="transactions"),
    path("transaction-detail/<transaction_id>", transaction.transaction_detail, name="transaction-detail"),
    
    # Paymennt Requests
    path("request-search-users/", payment_request.search_users_request, name="request-search-users"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-process/<account_number>/", payment_request.amount_request_process, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("amount-request-dispatch/<account_number>/<transaction_id>/", payment_request.amount_request_dispatch, name="amount-request-dispatch"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.amount_request_completed, name="amount-request-completed"),
    
    # Payment Request Settlement 
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),

    # Delete Payment Request 
    path("cancel-payment-request/<transaction_id>/", payment_request.cancel_payment_request, name="cancel-payment-request"),

    # Card Details
    path("card/<card_id>/", credit_card.card_detail, name="card-details"),
    path("fund-card/<card_id>/", credit_card.fund_card, name="fund-card"),  
    path("withdraw-from-card/<card_id>/", credit_card.withdraw_from_card, name="withdraw-from-card"),      
    path("remove-card/<card_id>/", credit_card.remove_card, name="remove-card"),    
]

kcoin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("user_auths.urls")),
    path("account/", include("account.urls")),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/payment_request/amount-request-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% load custom_filters %}
    {% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                        <div class="icon-area">
                            {% comment %} <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon"> {% endcomment %}
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Submitted</h3>
                            <p>Payment request <small><b> <u>{{transaction.transaction_id}}</u> of ({{transaction.amount}})KSH</b></small> was sent to <b>{{transaction.recipient}}</b></p>
                            <hr>
                            <a href=""><small>View Details</small></a> | <a href="{% url "core:request-search-users" %}"><small>Send another request</small></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/payment_request/amount-request-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% load custom_filters %}
    {% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                        <div class="icon-area">
                            {% comment %} <img src="{% static 'assets/images/icon/support-icon.png' %}" alt="icon"> {% endcomment %}
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Request</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account_query.user.kyc.image.url }}" style="width: 90px; height:90px; border-radius:50%; object-fit:cover;" alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account_query.user.username }}</p>
                                        <span class="mdr"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="541c312639353a6761143339353d387a373b39">{{ account_query.user.email }}</a></span><br>
                                        <span class="mdr">{{account_query.account_number}}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="javascript:void(0)">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Request Details</h6>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Requested Amount:</span>
                                        <b>{{ transaction.amount }} KSH</b>
                                    </li>
                                    <li>
                                        <span>Requested From:</span>
                                        <b>{{ account_query.kyc.full_name }} KSH</b>
                                    </li>
                                    <li>
                                        <span>Transaction Fee:</span>
                                        <b>Temporarily Free</b>
                                    </li>
                                    <li>
                                        <span>Purpose of Request:</span>
                                        <b>{{ transaction.payment_description }}</b>
                                    </li>
                                    <li>
                                        <span>Request Inititation Time:</span>
                                        <b> {{transaction.date }} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the request details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">Previous Step</a>
                            <a href="javascript:void(0)" type="submit" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Request</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">Request</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Request</h4>
                                            <p>Please enter your Personal Identification Number (PIN) below.</p>
                                            <form action="{% url "core:amount-request-dispatch" account_query.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Request was sent.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup end -->

    {% endblock content %}

templates/payment_request/amount-request.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% load custom_filters %}
    {% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount to Request</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    {% if account_query  %}
                                        <div class="img-area">
                                            <img src="{{ account_query.user.kyc.image.url }}" style="width: 100px; height:100px; border-radius:50%; object-fit:cover;" alt="image">
                                        </div>
                                        <div class="text-area">
                                            <p>{{account_query.user.kyc.full_name|title}}</p>
                                            <span class="mdr"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="773f12051a1619444237101a161e1b5914181a">{{account_query.user.email}}</a></span><br>
                                            <span class="mdr">{{account_query.account_number}}</span>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="right">
                                    <a href="{% url "core:search-account" %}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url "core:amount-request-process" account_query.account_number %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">Amount to Request</span>
                            <div class="input-area">
                                <input class="mdr" placeholder="Enter Amount" type="number" name="amount-request" id="amount-request">
                            </div>
                            <br>
                            <span class="mdr">Request Description</span>
                            <div class="input-area">
                                <input class="mdr" onkeyup="CalculateBalance()" placeholder="Purpose of Request (e.g., School Fees)" type="text" name="description">
                            </div>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="{% url "core:request-search-users" %}">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius:19px; background: #d85a45; color: #fff; " class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
     
    {% endblock content %}

templates/payment_request/settlement-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% load custom_filters %}
    {% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Settle Payment Request</h4>
                        <div class="icon-area">
                            {% comment %} <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon"> {% endcomment %}
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Completed</h3>
                            <p>Payment request <small><b><u>{{transaction.transaction_id}}</u></b></small> from <b>{{account.user.kyc.full_name}}</b> was settled successfully.</p>
                            <hr>
                            <a href=""><small>View Details</small></a> | <a href=""><small>Send another Payment</small></a> | <a href="{% url "account:dashboard" %}"><small>View Dashboard</small></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/payment_request/settlement-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% load custom_filters %}
    {% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Settle Payment Request</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Settlement</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account_query.user.kyc.image.url }}" style="width: 90px; height:90px; border-radius:50%; object-fit:cover;" alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account_query.user.username }}</p>
                                        <span class="mdr"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="541c312639353a6761143339353d387a373b39">{{ account_query.user.email }}</a></span><br>
                                        <span class="mdr">{{account_query.account_number}}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Settlement Details</h6>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Amount Requested:</span>
                                        <b>{{ transaction.amount }} KSH</b>
                                    </li>
                                    <li>
                                        <span>Recipient's Email:</span>
                                        <b><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="d3bebca1a1baa0e1e193b4beb2babffdb0bcbe"> {{ transaction.sender.email }} </a></b>
                                    </li>
                                    <li>
                                        <span>Transaction Fee:</span>
                                        <b>Temporarily Free</b>
                                    </li>
                                    <li>
                                        <span>Purpose of Settlement:</span>
                                        <b>{{ transaction.payment_description }}</b>
                                    </li>
                                    <li>
                                        <span>Transfer Inititation Time:</span>
                                        <b> {{transaction.date }} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the settlement details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="{% url "core:transactions" %}">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Settle</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Please enter your Personal Identification Number (PIN) below.</p>
                                            <form action="{% url "core:settlement-processing" account_query.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Request was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup end -->

    {% endblock content %}